baseURL = "http://afonsograca.com/"
languageCode = "en-gb"
title = "Afonso Graça"
theme = "hello-friend-ng"

[params]
  author = "Afonso Graça"
  description = "Afonso Graça is a software developer, a UX enthusiast and an OSS aficionado. He is also a music-lover and a concert-goer."
  title = "Afonso Graça — Software Developer"
  keywords = "Afonso Graça, Afonso, Graça, Software, Software Development, iOS, Swift, Objective-C"

[taxonomies]
  series = "series"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/afonsograca/"

[[params.social]]
  name = "github"
  url  = "https://github.com/afonsograca"
  
[[params.social]]
  name = "stackoverflow"
  url  = "https://stackoverflow.com/users/798731/afonso"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/AfonsoGraca"

[params.favicon.color]
  mask = "#f5f5f5"
  theme = "#f5f5f5"
  msapplication = "#f5f5f5"
